name: developにプッシュしたらmainにPR作る
on:
  push:
    branches:
      - develop
jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Create release pr
        run: gh pr create -B "stage" -t "Develop" -b ""