name: developにプッシュしたらmainにPR作る
on:
  push:
    branches:
      - develop
jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      # リリース用PRが既に存在するかどうかをチェック
      - name: Check if pr exists
        id: check_pr
        run: |
          pr_title=${{ (github.ref == 'refs/heads/staging' && '[本番]リリース') || '[ステージング]リリース' }}
          base_branch=${{ (github.ref == 'refs/heads/staging' && 'main') || 'staging' }}
          head_branch=${{ (github.ref == 'refs/heads/staging' && 'staging') || 'develop' }}
          echo "::set-output name=count::$(gh pr list -S ${pr_title}' in:title' -B $base_branch | wc -l)"
          echo "::set-output name=pr_title::$pr_title"
          echo "::set-output name=base_branch::$base_branch"
          echo "::set-output name=head_branch::$head_branch"
      # リリース用PRを作成
      - name: Create release pr
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create -B ${{ steps.check_pr.outputs.base_branch }} -H ${{ steps.check_pr.outputs.head_branch }} -t ${{ steps.check_pr.outputs.pr_title }} -b ""