name: PRのマージに反応してもらう
on:
  # pull_request:
  #   branches:
  #     - staging
  #   types:
  #     - closed
  push:
    branches: [staging]
jobs:
  hoge123:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_TITLE: '[hotfix]STG環境のhotfixをdevに反映'
    
    steps:
      - uses: actions/checkout@v3

      # 各種ブランチの名前を取得.
      - name: Check refs names.
        id: check_name
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}

      # # 同じタイトルのPRの件数確認
      # - name: Check PR count with same title.
      #   id: check_pr_count
      #   run: |
      #     echo "::set-output name=count::$(gh pr list -S ${PR_TITLE}' in:title' -B develop | wc -l)"

      # # ブランチ名がhotfixであり、かつ同じタイトルのPRがなければ、stagingをdevelopにマージするPRを作成
      # - name: Create PR to merge hotfix into develop
      #   if: contains(github.head_ref, 'hotfix') && steps.check_pr_count.outputs.count == 0
      #   run: |
      #     gh pr create -B develop -H staging -t ${PR_TITLE} -b ""

