name: PRのマージに反応してもらう
on:
  pull_request:
    branches:
      - staging
    types:
      - closed
jobs:
  hoge123:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_TITLE: '[hotfix]STG環境のhotfixをdevに反映'
    
    steps:
      - uses: actions/checkout@v3

      # 同じタイトルのPRの件数確認
      - name: Check PR count with same title.
        id: check_pr_count
        run: |
          echo "::set-output name=count::$(gh pr list -S ${PR_TITLE}' in:title' -B develop | wc -l)"

      # ブランチ名がhotfixであり、かつ同じタイトルのPRがなければ、stagingをdevelopにマージするPRを作成
      - name: Create PR to merge hotfix into develop
        if: contains(github.head_ref, 'hotfix') && steps.check_pr_count.outputs.count == 0
        run: |
          gh pr create -B develop -H staging -t ${PR_TITLE} -b ""

