on:
  pull_request:
    branches:
      - stating
    types:
      - closed
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo '2' ${{ github.ref }}
        echo '3' ${{ github.ref_name }}
        echo '4' ${{ github.head_ref }}
        echo '5' ${{ github.base_ref }}
